name: 'CI/CD'

on:
  push:
    paths:
      - 'terraform/test/**'
  pull_request:
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTON_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  WORKING_DIR: ./terraform/test

jobs:
  dev_stage:
    name: 'DEV-STAGE'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      working-directory: ${{env.WORKING_DIR}}
    
    - name: Terraform workspace dev
      run: terraform workspace select dev || terraform workspace new dev
      working-directory: ${{env.WORKING_DIR}}

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ${{env.WORKING_DIR}}

    - name: Terraform Plan
      run: terraform plan
      working-directory: ${{env.WORKING_DIR}}
      env:
        TF_VAR_subscription_id: "${{env.ARM_SUBSCRIPTON_ID}}"

    #- name: Terraform Apply
    #  run: terraform apply -auto-approve -input=false

  stage_prod:
    name: 'STAGE-PROD'
    needs: dev_stage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      working-directory: ${{env.WORKING_DIR}}
    
    - name: Terraform workspace stage
      run: terraform workspace select stage || terraform workspace new stage
      working-directory: ${{env.WORKING_DIR}}

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ${{env.WORKING_DIR}}

    - name: Terraform Plan
      run: terraform plan
      working-directory: ${{env.WORKING_DIR}}
      env:
        TF_VAR_subscription_id: "${{env.ARM_SUBSCRIPTON_ID}}"

    #- name: Terraform Apply
    #  run: terraform apply -auto-approve -input=false

  prod:
    name: 'PROD'
    needs: stage_prod
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      working-directory: ${{env.WORKING_DIR}}
    
    - name: Terraform workspace stage
      run: terraform workspace select prod || terraform workspace new prod
      working-directory: ${{env.WORKING_DIR}}

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ${{env.WORKING_DIR}}

    - name: Terraform Plan
      run: terraform plan
      working-directory: ${{env.WORKING_DIR}}
      env:
        TF_VAR_subscription_id: "${{env.ARM_SUBSCRIPTON_ID}}"

    #- name: Terraform Apply
    #  run: terraform apply -auto-approve -input=false
