name: 'Develop'

on:
  push:
    branches:
      - develop
    paths:
      - 'terraform/webapp/**'
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  TF_VAR_database_user: ${{ secrets.DATABASE_USER }}
  TF_VAR_database_pass: ${{ secrets.DATABASE_PASS }}
  WORKING_DIR: "./terraform/webapp"

jobs:
  stage:
    name: 'Develop'
    runs-on: ubuntu-latest
    environment: development
    defaults:
      run:
        shell: bash
        working-directory: "${{ env.WORKING_DIR }}"

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
    
    - name: Terraform workspace dev
      run: terraform workspace select -or-create dev

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false

    - name: Test dev web app
      run: curl "https://$(terraform output -raw app_domain)"

    - name: Output web app URL to PR summary
      run: |
        app_domain=$(terraform output -raw app_domain)
        echo "DEV web app URL: https://$app_domain" >> $GITHUB_STEP_SUMMARY
