name: 'Stage to prod'

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/webapp/**'
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTON_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  WORKING_DIR: ./terraform/webapp

jobs:
  stage:
    name: 'Stage'
    runs-on: ubuntu-latest
    environment: staging

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      working-directory: ${{env.WORKING_DIR}}
    
    - name: Terraform workspace stage
      run: terraform workspace select -or-create stage
      working-directory: ${{env.WORKING_DIR}}

    # - name: Terraform Plan
    #   run: terraform plan
    #   working-directory: ${{env.WORKING_DIR}}
    #   env:
    #     TF_VAR_subscription_id: "${{env.ARM_SUBSCRIPTON_ID}}"

    #- name: Terraform Apply
    #  run: terraform apply -auto-approve -input=false

  prod:
    name: 'Prod'
    needs: stage
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      working-directory: ${{env.WORKING_DIR}}
    
    - name: Terraform workspace prod
      run: terraform workspace select -or-create prod
      working-directory: ${{env.WORKING_DIR}}

    # - name: Terraform Plan
    #   run: terraform plan
    #   working-directory: ${{env.WORKING_DIR}}
    #   env:
    #     TF_VAR_subscription_id: "${{env.ARM_SUBSCRIPTON_ID}}"

    #- name: Terraform Apply
    #  run: terraform apply -auto-approve -input=false
