name: 'Validate'

on:
  push: # Should run on update to all files since it will block the PR
    branches-ignore: # Main and develop have already been validates in the PR
      - main
      - develop
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      WORKING_DIR: ./terraform/webapp
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      working-directory: ${{env.WORKING_DIR}}

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ${{env.WORKING_DIR}}

    - name: Terraform Validate
      run: terraform validate
      working-directory: ${{env.WORKING_DIR}}
    
    - name: Run tfsec
      uses: aquasecurity/tfsec-action@v1.0.3
      with:
        working_directory: ${{env.WORKING_DIR}}
        github_token: ${{ env.GITHUB_TOKEN }}
        soft_fail: true # avoid breaking the build
