name: 'Validate'

on:
  push: # Should run on update to all files since it will block the PR
    branches-ignore: # Main and develop have already been validates in the PR
      - main
      - develop
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  WORKING_DIR: ./terraform/webapp
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: "${{ env.WORKING_DIR }}"

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate
    
    - name: Run tfsec
      uses: aquasecurity/tfsec-action@v1.0.3
      with:
        github_token: ${{ env.GITHUB_TOKEN }}
        soft_fail: true # avoid breaking the build
